name: testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup JBang
      uses: jbangdev/setup-jbang@main

    - name: Start tmate session
      uses: mxschmitt/action-tmate@v3

